### ISSUE TITLE
How much programming do cybersecurity professionals do?

### ISSUE THREAD

**Issue by tweedge** [r-cybersecurity/faq#3]
"It depends."

Inspiring answer: https://www.reddit.com/r/cybersecurity/comments/onpu1q/how_do_cybersecurity_professionals_use/h5tbnuo?utm_source=share&utm_medium=web2x&context=3

**Comment by deividluchi** [comment]
I can write this one

**Comment by tweedge** [comment]
Sounds good! It has been assigned to you. I'll confirm the licensing prior to merging. Good luck and please let me know if you need anything!
